resolver: lts-15.4

extra-deps:
- tasty-rerun-1.1.14
- fgl-visualize-0.1.0.1
- located-base-0.1.1.1
- hashable-1.3.0.0
- Diff-0.3.4
- text-format-0.3.2
- optics-0.3
- optics-core-0.3
- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: 3bc467162ba285bf2c1529dafce21a20bb9aab8e
  subdirs:
    - .
    - liquid-ghc-prim
    - liquid-base
- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: a4e303bc55e8f596893e661954e20c983a61215f

allow-newer: true
compiler: ghc-8.10.1
